FROM debian:latest

RUN apt-get update && apt-get install -y python3-django python3-pip vim nginx python3-dev libpq-dev \
RUN pip3 install --no-cache-dir -r requirements.txt

# COPY ../ .

# CMD [ "python", "./your-daemon-or-script.py" ]
