# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171011_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exceptionlog',
            old_name='client_login_id',
            new_name='login_client_id',
        ),
        migrations.AlterField(
            model_name='login',
            name='date_expired',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
