# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171012_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
