# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171013_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone2',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
