# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171016_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=150)),
                ('compound', models.BooleanField(null=True)),
                ('unit_weight', models.IntegerField(choices=[(1, 'kg (Kilograma)'), (2, 'L (Litros)'), (3, 'Kb (Kilobytes)')])),
                ('weight', models.FloatField(null=True)),
                ('width', models.FloatField(null=True)),
                ('length', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('origin', models.IntegerField(choices=[(1, 'Própria'), (2, 'Terceirizado'), (3, 'Importado')])),
                ('gtin', models.CharField(max_length=150, null=True)),
                ('published', models.BooleanField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-product_id'],
                'db_table': 'product',
            },
        ),
    ]
