# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171102_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cnpj',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
