# Generated by Django 2.0 on 2017-12-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_order_orderproduct'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderproduct',
            unique_together={('order', 'product')},
        ),
    ]
